# Generated by Django 5.1.7 on 2025-03-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('accessories', models.TextField(default='full', max_length=4)),
                ('info', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazva', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.TextField(max_length=20, null=True)),
                ('model', models.TextField(max_length=30, null=True)),
                ('color', models.TextField(max_length=15, null=True)),
                ('warranty', models.TextField(default='12 місяців', max_length=17)),
                ('uls', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
