# Generated by Django 5.1.7 on 2025-03-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_electro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='price2',
        ),
    ]
