# Generated by Django 5.1.7 on 2025-03-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_electro', '0002_remove_category_price2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
