# Generated by Django 5.1.7 on 2025-04-01 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_electro', '0003_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_electro.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nazva',
            field=models.CharField(max_length=100, unique=True, verbose_name='nazv'),
        ),
    ]
