# Generated by Django 5.1.7 on 2025-04-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_electro', '0004_product_category_alter_product_nazva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='has_discount',
            field=models.BooleanField(default=False, verbose_name='Знижка'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Зображення'),
        ),
        migrations.AddField(
            model_name='category',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='В наявності'),
        ),
        migrations.AlterField(
            model_name='category',
            name='accessories',
            field=models.CharField(choices=[('full', 'Повна'), ('basic', 'Базова'), ('none', 'Відсутні')], default='full', max_length=5, verbose_name='Комплектація'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=20, null=True, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'Чорний'), ('white', 'Білий'), ('red', 'Червоний'), ('blue', 'Синій'), ('green', 'Зелений'), ('other', 'Інший')], max_length=15, null=True, verbose_name='Колір'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=30, null=True, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nazva',
            field=models.CharField(max_length=100, unique=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price1',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(choices=[('6 months', '6 місяців'), ('12 months', '12 місяців'), ('24 months', '24 місяці'), ('no warranty', 'Без гарантії')], default='12 months', max_length=17, verbose_name='Гарантія'),
        ),
    ]
