# Generated by Django 5.1.7 on 2025-04-05 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_electro', '0005_remove_product_category_category_has_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True,blank=True, on_delete=django.db.models.deletion.CASCADE, to='site_electro.category', verbose_name='Категорія'),
        ),
    ]
