# Generated by Django 5.1.7 on 2025-04-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_electro', '0009_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
