# Generated by Django 5.1.7 on 2025-04-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_electro', '0011_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='price2',
        ),
    ]
