# Generated by Django 5.1.7 on 2025-04-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_electro', '0012_remove_category_price2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='info',
        ),
        migrations.AddField(
            model_name='category',
            name='components',
            field=models.BooleanField(default=False, verbose_name='Компоненти'),
        ),
        migrations.AddField(
            model_name='category',
            name='contacts',
            field=models.BooleanField(default=False, verbose_name='Контакти'),
        ),
        migrations.AddField(
            model_name='category',
            name='lights',
            field=models.BooleanField(default=False, verbose_name='Ліхтарі'),
        ),
        migrations.AddField(
            model_name='category',
            name='works',
            field=models.BooleanField(default=False, verbose_name='Роботи'),
        ),
    ]
