# Generated by Django 5.1.7 on 2025-04-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_electro', '0013_remove_category_info_category_components_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='components',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Компоненти'),
        ),
        migrations.AlterField(
            model_name='category',
            name='contacts',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Контакти'),
        ),
        migrations.AlterField(
            model_name='category',
            name='lights',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ліхтарі'),
        ),
        migrations.AlterField(
            model_name='category',
            name='works',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Роботи'),
        ),
    ]
