# Generated by Django 5.1.7 on 2025-04-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_electro', '0014_alter_category_components_alter_category_contacts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
