# Generated by Django 5.1.7 on 2025-04-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_electro', '0015_remove_category_description_remove_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uls',
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(choices=[('1 months', '1 місяців'), ('6 months', '6 місяців'), ('12 months', '12 місяці'), ('no warranty', 'Без гарантії')], default='1 months', max_length=17, verbose_name='Гарантія'),
        ),
    ]
