# Generated by Django 5.1.7 on 2025-04-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_electro', '0017_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'Чорний'), ('white', 'Білий'), ('red', 'Червоний'), ('blue', 'Синій'), ('yellow', 'Зелений'), ('other', 'Інший')], max_length=15, null=True, verbose_name='Колір'),
        ),
    ]
