# Generated by Django 5.1.7 on 2025-04-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_electro', '0018_alter_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Посилання на Telegram')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'Чорний'), ('white', 'Білий'), ('red', 'Червоний'), ('blue', 'Синій'), ('yellow', 'Жовтий'), ('other', 'Інший')], max_length=15, null=True, verbose_name='Колір'),
        ),
    ]
