# Generated by Django 5.1.7 on 2025-04-21 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_electro', '0019_contactinfo_alter_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='site_electro.product')),
                ('component_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип компонента')),
            ],
            bases=('site_electro.product',),
        ),
        migrations.CreateModel(
            name='Lights',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='site_electro.product')),
                ('work_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Час роботи від акумулятора')),
            ],
            bases=('site_electro.product',),
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='site_electro.product')),
                ('work_type', models.CharField(blank=True, choices=[('light', 'Ліхтар'), ('speaker', 'Колонка'), ('collection', 'збірка'), ('instrument', 'прилад'), ('other', 'Інше')], max_length=20, null=True, verbose_name='Тип роботи')),
            ],
            bases=('site_electro.product',),
        ),
    ]
