# Generated by Django 5.1.7 on 2025-04-21 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_electro', '0020_components_lights_works'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='component_type',
        ),
    ]
