# Generated by Django 5.1.7 on 2025-04-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_electro', '0022_components_component_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='component_type',
        ),
    ]
