# Generated by Django 5.1.7 on 2025-04-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_electro', '0024_components_component_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='times',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Час роботи'),
        ),
    ]
