# Generated by Django 5.1.7 on 2025-04-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_electro', '0025_works_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва роботи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис роботи')),
                ('times', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Час роботи')),
                ('work_type', models.CharField(blank=True, choices=[('light', 'Ліхтар'), ('speaker', 'Колонка'), ('collection', 'Збірка'), ('instrument', 'Прилад'), ('other', 'Інше')], max_length=20, null=True, verbose_name='Тип роботи')),
            ],
        ),
        migrations.DeleteModel(
            name='Works',
        ),
    ]
