# Generated by Django 5.1.7 on 2025-05-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_electro', '0027_work_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='telegram_group',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на Telegram(група)'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='telegram_link',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на Telegram(особисто)'),
        ),
    ]
