# Generated by Django 5.1.7 on 2025-06-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_electro', '0028_contactinfo_telegram_group_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lights',
            new_name='Photo',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='lights',
            new_name='photos',
        ),
    ]
