# Generated by Django 5.1.7 on 2025-06-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_electro', '0029_rename_lights_photo_rename_lights_category_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='product_ptr',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
        migrations.RemoveField(
            model_name='category',
            name='accessories',
        ),
        migrations.RemoveField(
            model_name='category',
            name='components',
        ),
        migrations.RemoveField(
            model_name='category',
            name='has_discount',
        ),
        migrations.RemoveField(
            model_name='category',
            name='works',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='work_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='photos',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фото'),
        ),
        migrations.DeleteModel(
            name='Components',
        ),
    ]
