# Generated by Django 5.1.7 on 2025-06-25 12:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_electro', '0030_remove_components_product_ptr_delete_work_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=100, null=True, verbose_name="Ваше ім'я")),
                ('author_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Ваш Email')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг (від 1 до 5)')),
                ('comment', models.TextField(verbose_name='Ваш відгук')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Затверджено модератором')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='site_electro.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-created_at'],
            },
        ),
    ]
