# Generated by Django 5.1.7 on 2025-06-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_electro', '0031_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price1',
        ),
    ]
